### ISSUE TITLE
After loading buildpack,  /js/bundle.js no longer loads.

### ISSUE THREAD

**Issue by ACPK** [gjaldon/heroku-buildpack-phoenix-static#11]

**Comment by ericmj** [comment]
What do you mean "no longer loads"? Do you get a specific error?

**Comment by gjaldon** [comment]
@ACPK, @ericmj is right. We'll need a bit more info on this. Is this the issue you pointed out in Slack or is this something else? Let us know if it hasn't been addressed yet.
