### ISSUE TITLE
Install sass

### ISSUE THREAD

**Issue by tispratik** [gjaldon/heroku-buildpack-phoenix-static#12]
This buildpack should probably install sass as well, because when we `import @compass` in our scss files, heroku fails to build.

```
remote:        Running default compile
remote:        You need to have Sass on your system
remote:        Execute `gem install sass`
```

**Comment by tispratik** [comment]
Similar to https://github.com/Label305-Forks/heroku-buildpack-nodejs-sass

**Comment by pragmaticivan** [comment]
@tispratik maybe you can copy the code from compile of this nodejs-sass and overwrite into the compile of this buildpack, so you can install just in your env.

**Comment by gjaldon** [comment]
Feel free to reopen if this is still needed
