### ISSUE TITLE
Stop the deploy if asset building fails?

### ISSUE THREAD

**Issue by joakimk** [gjaldon/heroku-buildpack-phoenix-static#20]
I have a small non-production app I'm building and the assets failed to compile on deploy when using this buildpack, but the deploy continued on anyways leading to a deploy with broken assets.

Could this be fixed by adding `set -e` to prevent the scripts from advancing when a command fails?

**Comment by tute** [comment]
Sample output:

```
remote:        pushserve@1.0.2 /tmp/build_76e26eb4ea4516b77935752d334bb8d9/node_modules/pushserve
remote:        npm WARN package.json @ No license field.
remote:        Running default compile
remote:        26 May 17:26:22 - error: Compiling of web/static/css/app.scss failed. File to import not found or unreadable: neat
remote:        Parent style sheet: /tmp/build_76e26eb4ea4516b77935752d334bb8d9/web/static/css/app.scss
remote:        Check your digested files at "priv/static"
remote:
remote: -----> Finalizing build
remote:        Creating runtime environment
remote:
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
[...]
```

It was confusing for me at first, as the error message gets lost in the output.

**Comment by gjaldon** [comment]
https://github.com/gjaldon/heroku-buildpack-phoenix-static/commit/f45d8ce696e7593059eb978ae631756fb2e4d744 should address the issues mentioned here. Let me know if it's still a problem.
