### ISSUE TITLE
Error deploying Phoenix under umbrella

### ISSUE THREAD

**Issue by seantanly** [gjaldon/heroku-buildpack-phoenix-static#21]
I'm having trouble deploying a Phoenix app when it is under an umbrella project. Below are the errors from console. Am I missing something?

If it isn't currently supported, what can we do to support it?

The umbrella app is available at https://github.com/seantanly/elixir-myumbrella

When not using umbrella, the same deployment configurations works. https://github.com/seantanly/elixir-webfront

Errors from console (myumbrella),
```
=====> Downloading Buildpack: https://github.com/gjaldon/heroku-buildpack-phoenix-static
=====> Detected Framework: Phoenix

-----> Loading configuration and environment
       Loading config...
       Will use the following versions:
       * Node 5.6.0
       Will export the following config vars:
       * Config vars DATABASE_URL
       * MIX_ENV=prod

-----> Installing binaries
       Using cached node 5.6.0...
       Installing node 5.6.0...
       Using default npm version

-----> Building dependencies
       Installing and caching node modules
remote: cp: cannot stat '/cache/node_modules/*': No such file or directory
       npm WARN enoent ENOENT: no such file or directory, open '/tmp/build/package.json'
       npm WARN build No description
       npm WARN build No repository field.
       npm WARN build No README data
       npm WARN build No license field.
       npm ERR! Linux 3.13.0-71-generic
       npm ERR! argv "/tmp/build/.heroku/node/bin/node" "/tmp/build/.heroku/node/bin/npm" "--unsafe-perm" "prune"
       npm ERR! node v5.6.0
       npm ERR! npm  v3.6.0
       npm ERR! path /tmp/build/package.json
       npm ERR! code ENOENT
       npm ERR! errno -2
       npm ERR! syscall open

       npm ERR! enoent ENOENT: no such file or directory, open '/tmp/build/package.json'
       npm ERR! enoent ENOENT: no such file or directory, open '/tmp/build/package.json'
       npm ERR! enoent This is most likely not a problem with npm itself
       npm ERR! enoent and is related to npm not being able to find a file.
       npm ERR! enoent

       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build/npm-debug.log
       Running default compile
       /tmp/buildpackclV6M/compile: line 1: brunch: command not found
       warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
==> webfront
       The input path "priv/static" does not exist
```

**Comment by gjaldon** [comment]
Thanks again @seantanly!

**Comment by simonh1000** [comment]
The link to the my-umbrella repo no longer works. I'm looking for an example of the config you used to deploy an umbrella project to heroku. (In my case it is json only so I do not need this buildpack, but this was the only thing on the internet I could find that appeared to have achieved the end goal)

**Comment by seantanly** [comment]
@simonh1000 yea, I deleted the my-umbrella repo after the issue is resolved. If you follow the `phoenix_static_buildpack.config` found on the `README.md` and modify the `phoenix_relative_path` variable to point to your phoenix app as shown, it should work.

**Comment by xn4v8h** [comment]
@seantanly what's the syntax if you have two phoenix apps in your umbrella (i.e. an admin app, and your web app)

**Comment by seantanly** [comment]
@xn4v8h I believe currently this buildpack doesn't support multiple Phoenix apps under the same umbrella project.

**Comment by wojtekmach** [comment]
as a workaround I've added a custom `compile` file at the root of the umbrella: https://github.com/wojtekmach/acme_bank/blob/master/compile, so this might work for your use case too. There's more stuff do to, e.g. caching assets between rebuilds currently doesn't work for the 2nd phoenix app
