### ISSUE TITLE
Assets are not compiled in an umbrella project

### ISSUE THREAD

**Issue by MMore** [gjaldon/heroku-buildpack-phoenix-static#24]
Hi,

I have a similar problem like in https://github.com/gjaldon/heroku-buildpack-phoenix-static/pull/22 and in https://github.com/gjaldon/heroku-buildpack-phoenix-static/issues/21. I tried these described fixes there, but that didn't help :(.

So this is the log from the console:

		remote: -----> Creating .profile.d with env vars
		remote: -----> Writing export for multi-buildpack support
		remote: -----> Fetching set buildpack https://github.com/gjaldon/heroku-buildpack-phoenix-static.git... done
		remote: -----> Phoenix app detected
		remote:
		remote: -----> Loading configuration and environment
		remote:        Loading config...
		remote:        Will use the following versions:
		remote:        * Node 5.3.0
		remote:        Will export the following config vars:
		remote:        * Config vars DATABASE_URL
		remote:        * MIX_ENV=prod
		remote:
		remote: -----> Installing binaries
		remote:        Downloading node 5.3.0...
		remote:        Installing node 5.3.0...
		remote:        Using default npm version
		remote:
		remote: -----> Building dependencies
		remote:        Installing and caching node modules
		remote:        npm ERR! addLocal Could not install /tmp/build_66b1378fa026372e48b85ad01cd87044/apps/my_phoenix_app/deps/phoenix
		remote:        npm ERR! addLocal Could not install /tmp/build_66b1378fa026372e48b85ad01cd87044/apps/my_phoenix_app/deps/phoenix_html
		remote:        npm ERR! Linux 3.13.0-85-generic
		remote:        npm ERR! argv "/tmp/build_66b1378fa026372e48b85ad01cd87044/.heroku/node/bin/node" "/tmp/build_66b1378fa026372e48b85ad01cd87044/.heroku/node/bin/npm" "install" "--quiet" "--unsafe-perm" "--userconfig" "/tmp/build_66b1378fa026372e48b85ad01cd87044/npmrc"
		remote:        npm ERR! node v5.3.0
		remote:        npm ERR! npm  v3.3.12
		remote:        npm ERR! path /tmp/build_66b1378fa026372e48b85ad01cd87044/apps/my_phoenix_app/deps/phoenix
		remote:        npm ERR! code ENOENT
		remote:        npm ERR! errno -2
		remote:        npm ERR! syscall open
		remote:
		remote:        npm ERR! enoent ENOENT: no such file or directory, open '/tmp/build_66b1378fa026372e48b85ad01cd87044/apps/my_phoenix_app/deps/phoenix'
		remote:        npm ERR! enoent This is most likely not a problem with npm itself
		remote:        npm ERR! enoent and is related to npm not being able to find a file.
		remote:        npm ERR! enoent
		remote:
		remote:        npm ERR! Please include the following file with any support request:
		remote:        npm ERR!     /tmp/build_66b1378fa026372e48b85ad01cd87044/apps/my_phoenix_app/npm-debug.log
		remote:        npm WARN package.json @ No license field.
		remote: cp: cannot stat ‘node_modules’: No such file or directory
		remote:        Running default compile
		remote:        /tmp/buildpack20160516-166-kt4k5o/compile: line 1: brunch: command not found
		remote:        ==> data_manager
		remote:        Compiled lib/data_manager/hashing.ex
		remote:        Compiled lib/data_manager.ex
		remote:        Compiled lib/data_manager/read.ex
		remote:        Generated data_manager app
		remote:        The input path "priv/static" does not exist
		remote:        ==> my_phoenix_app
		remote:
		remote: -----> Finalizing build
		remote:        Creating runtime environment
		remote:
		remote: -----> Discovering process types
		remote:        Procfile declares types     -> (none)
		remote:        Default types for buildpack -> web
		remote:
		remote: -----> Compressing...
		remote:        Done: 86.5M
		remote: -----> Launching...
		remote:        Released v13

**Comment by gjaldon** [comment]
@MMore could you share with me your app without the application code? It would be helpful for troubleshooting this issue.

**Comment by MMore** [comment]
@gjaldon of course! I am curious what the issue is.

https://github.com/MMore/heroku_build_pack_phoenix_static_test_case

**Comment by gjaldon** [comment]
@MMore sorry for the late response. Finally got to testing out deploying your app. The error has to do with your `apps/phoenix_app/package.json` file. You'll need to edit it to look like:

```
{
  "repository": {
  },
  "dependencies": {
    "babel-brunch": "~6.0.0",
    "brunch": "~2.1.3",
    "clean-css-brunch": "~1.8.0",
    "css-brunch": "~1.7.0",
    "javascript-brunch": "~1.8.0",
    "uglify-js-brunch": "~1.7.0",
    "phoenix": "file:../../deps/phoenix",                      # This line was changed
    "phoenix_html": "file:../../deps/phoenix_html"     # This line was changed
  }
}
```

You'll need to point `phoenix` and `phoenix_html` to the correct `deps` directory.

**Comment by MMore** [comment]
Thanks!
