### ISSUE TITLE
Create a version tag for this repo

### ISSUE THREAD

**Issue by col** [gjaldon/heroku-buildpack-phoenix-static#26]
I'd like to pin my dokku app to a specific version of this buildpack to avoid any surprises in the future. Can you create a tag at a logical point so that I can specify a version?

See details here: https://github.com/dokku/dokku/blob/master/docs/deployment/buildpacks.md#using-a-specific-buildpack-version

The tag should be in the format of 'v1' 
Example: https://github.com/HashNuke/heroku-buildpack-elixir/releases

**Comment by gjaldon** [comment]
@col just created a release for this repo based off of the latest commit. Did you need a release for an earlier point in this project's history?
