### ISSUE TITLE
Node modules cache push rejected

### ISSUE THREAD

**Issue by jansta** [gjaldon/heroku-buildpack-phoenix-static#28]
Hi!

I haven't touched my project for some time. I just wanted to push it to heroku with minimal changes but it does not work anymore. I'm not using any node modules in this project / I have no node_modules folder in my project. Any idea on how to get it running? Thanks!

remote:
remote: -----> Building dependencies
remote:        Installing and caching node modules
remote: cp: cannot stat ‘/app/tmp/cache/node_modules/*’: No such file or directory
remote:  !     Push rejected, failed to compile Phoenix app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:

**Comment by jansta** [comment]
I guess it has to do with the stricter enforcing of stopping the compiling if anything failed. (commit "stop script if anything fails")

**Comment by gjaldon** [comment]
@jansta if you're app doesn't have any static assets (js, css, etc...) then you don't need heroku-buildpack-phoenix-static.

**Comment by jansta** [comment]
I do have static assets, I just don't use node.js. I basically use Phoenix as a REST backend and put a static index.html with jquery in front of it. Does that make sense or does Phoenix implicitly require me to use node ?

**Comment by gjaldon** [comment]
@jansta If you do not have any build step for your static assets like `brunch build`, then you don't need this buildpack. This buildpack basically includes Node and gives you access to mix tasks so you can run `mix phoenix.digest`. If you're using Phoenix as REST API, then you shouldn't need this. :)

**Comment by jansta** [comment]
Ok - the deployment doesn't work without the phoenix buildpack, so I will have to take a deeper look on what's going on. Thanks!

**Comment by gjaldon** [comment]
You're welcome!
