### ISSUE TITLE
Add option to invalidate cache

### ISSUE THREAD

**Issue by gjaldon** [gjaldon/heroku-buildpack-phoenix-static#3]

**Comment by deepflame** [comment]
:+1:

**Comment by aerosol** [comment]
I suppose that could help me, I'm suddenly getting:

```
remote: -----> Installing binaries
remote:        Using cached node 0.12.4...
remote:        Installing node 0.12.4...
remote: mv: cannot move ‘/tmp/node-v0.12.4-linux-x64/bin’ to ‘/tmp/build_31b49ff677dbcc06cea25f1bdc6d466c/.heroku/node/bin’: Directory not empty
remote: mv: cannot move ‘/tmp/node-v0.12.4-linux-x64/include’ to ‘/tmp/build_31b49ff677dbcc06cea25f1bdc6d466c/.heroku/node/include’: Directory not empty
remote: mv: cannot move ‘/tmp/node-v0.12.4-linux-x64/lib’ to ‘/tmp/build_31b49ff677dbcc06cea25f1bdc6d466c/.heroku/node/lib’: Directory not empty
remote: mv: cannot move ‘/tmp/node-v0.12.4-linux-x64/share’ to ‘/tmp/build_31b49ff677dbcc06cea25f1bdc6d466c/.heroku/node/share’: Directory not empty
remote:  !     Push rejected, failed to compile Phoenix app.
remote:
remote:  !     Push failed
```

**Comment by aerosol** [comment]
Pretty sure this is related to https://github.com/gjaldon/heroku-buildpack-phoenix-static/commit/f45d8ce696e7593059eb978ae631756fb2e4d744 -- My last successful deploy was 6 days ago

**Comment by gjaldon** [comment]
@aerosol not sure why that directory is not empty. The build directory is supposed to be cleared out in between deploys. 

Anyway, just pushed a fix for this. Could you try out latest `master`?

**Comment by aerosol** [comment]
@gjaldon Yes that helped.

FWIW, the buildpacks I'm using:

```
1. https://github.com/HashNuke/heroku-buildpack-elixir.git
2. https://github.com/heroku/heroku-buildpack-nodejs
3. https://github.com/gjaldon/heroku-buildpack-phoenix-static.git
```

**Comment by aerosol** [comment]
Hm actually the static assets haven't been built, investigating.

**Comment by aerosol** [comment]
In case anyone else runs into this, I've removed `heroku-buildpack-nodejs` and configured `heroku-buildpack-phoenix-static` to use the recommended npm/node versions.

**Comment by gjaldon** [comment]
@aerosol you're earlier error was also related to using `heroku-buildpack-nodejs`. We now raise an error when `heroku-buildpack-nodejs` is used(can only be detected though when this buildpack is run after the nodejs one). I also added a small FAQ section to clarify that nodejs buildpack should not be used along with this buildpack.

**Comment by gjaldon** [comment]
@deepflame latest commits will remove the older Node version if you specify a different version of Node in your latest deploy. Will work on clearing the cache based on an option flag in the `phoenix_static_buildpack.config` file.

**Comment by gjaldon** [comment]
This feature of invalidating cache is now in master. You can enable it by setting `clean_cache=true` in the phoenix_buildpack_static.config file.
