### ISSUE TITLE
Set node version / npm version from package.json

### ISSUE THREAD

**Issue by YayC** [gjaldon/heroku-buildpack-phoenix-static#32]
It seems to be a best practice to specify node and npm versions within the package.json itself, under "engines" (see [heroku docs on deploying node apps](https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version)).

**Comment by gjaldon** [comment]
@YayConnolly thanks for opening this issue. Will look into supporting that with the next week.

**Comment by gjaldon** [comment]
Closing since this is in reference to the node buildpack from heroku. The current way of setting npm and node versions should be fine and the same with how heroku-buildpack-elixir does it
