### ISSUE TITLE
Include assets from previous build(s)

### ISSUE THREAD

**Issue by aaronjensen** [gjaldon/heroku-buildpack-phoenix-static#33]
At the moment, if you deploy a new version of a site with newly fingerprinted assets, the old assets will no longer be available.

This is not a problem if:
1. They're cached on a CDN (not guaranteed, even if you have a CDN)
2. You're not doing any dynamic loading of assets (theoretically even a regular page load could break if one of its assets it required became unavailable)

For other cases, especially SPAs with dynamic code loading this is a big problem.

I believe the rails build pack includes assets from past builds, though I'm not sure of the specifics. Ideally we could configure the number of old builds to maintain or a max age (I don't know if heroku's cache maintains file ages).

Thoughts on something like this? Thanks!

**Comment by aaronjensen** [comment]
Relevant code from sprockets: https://github.com/rails/sprockets/blob/master/lib/sprockets/manifest.rb#L248-L268

**Comment by gjaldon** [comment]
This doesn't seem necessary to me. Could you be clearer on when this would be needed? In particular, I don't get what you mean by: 
> You're not doing any dynamic loading of assets (theoretically even a regular page load could break if one of its assets it required became unavailable)
For other cases, especially SPAs with dynamic code loading this is a big problem.

**Comment by aaronjensen** [comment]
Some people wouldn't be too affected by this, but here's the scenario:

1. User A loads Version A of a SPA and downloads Asset A1.
2. You deploy Version B of your SPA which includes Asset B1 and B2.
3. User B navigates to another "page" in your single page app, which triggers a load of Asset A2. They get a 404 because you are currently serving Version B which does not include old assets.

Another scenario:

1. User A loads Version A of your app
2. Just as they're loading it, you're deploying Version B which includes a new logo file, Logo B.
3. User A's browser tries to load Logo A, but it's 404 because only Logo B is available.

From Heroku Support:

> As for what will happen when OLD html is loaded, and tries to retrieve old assets after the new dynos have been switched over, this is a very small window we're talking about, but here are my thoughts. There are some frameworks that handle this for you – for instance, with Ruby on Rails, it saves the past 3 versions of assets, which avoids this problem. That being said, I see that you're using some 3rd party buildpacks, which means this is something you'll want to build yourself (and in which case its probably easiest to store them on something like S3), or see if the buildpack developers have a way of doing this.

My post/proposal on phoenix-core (no replies yet) https://groups.google.com/forum/#!topic/phoenix-core/QRU-WUogUyI

**Comment by gjaldon** [comment]
Closing since it is no longer needed. Phoenix already handles this
