### ISSUE TITLE
Delete node_modules after compile

### ISSUE THREAD

**Issue by aaronjensen** [gjaldon/heroku-buildpack-phoenix-static#34]
There usually isn't any reason to include node_modules in your slug, so they should be nuked or it should at least be optional. It looks like `compile` runs after caching, so I'm going to add it to my compile step for now.

**Comment by gjaldon** [comment]
@aaronjensen doesn't the build directory need all of the app's deps in it? Have you tested this out?

**Comment by aaronjensen** [comment]
Yes, see #36. It works well, my slug is 50mb smaller, which makes deployment a little faster and gives more room for assets and such.

**Comment by gjaldon** [comment]
Ahh, I get it now. The node modules are not necessary after compile because the assets have been built. We typically use Node just to build assets in Phoenix. This is definitely useful!
