### ISSUE TITLE
Delete node after compile

### ISSUE THREAD

**Issue by aaronjensen** [gjaldon/heroku-buildpack-phoenix-static#35]
Similar to https://github.com/gjaldon/heroku-buildpack-phoenix-static/issues/34 most projects won't need node after compile so there's no reason to keep it around. It can at least be an option. 

I'm happy to contribute either or both of these if you think they'd be good additions.

**Comment by aaronjensen** [comment]
Actually it looks like `.slugignore` would work well for this. Maybe I can just update the README w/ suggestions?

**Comment by gjaldon** [comment]
I don't think removing Node from the build dir will work. :)

**Comment by aaronjensen** [comment]
removing node works fine as long as your app doesn't need node in runtime. If you only need node to compile assets it doesn't need to be in the slug.
