### ISSUE TITLE
Specifying node_version causes build to fail

### ISSUE THREAD

**Issue by ntilwalli** [gjaldon/heroku-buildpack-phoenix-static#46]
Hi. Thanks for providing this tool!  When I tried specifying a `node_version=6.9.1` in my `phoenix_static_buildpack.config` I consistently go errors like:
```
-----> Creating .profile.d with env vars
-----> Writing export for multi-buildpack support
-----> Phoenix app detected
-----> Loading configuration and environment
       Loading config...
       Will use the following versions:
       * Node 6.9.1
       Will export the following config vars:
       * Config vars DATABASE_URL
       * MIX_ENV=prod
-----> Installing binaries
       Downloading node 6.9.1
 !     Push rejected, failed to compile Phoenix app.
 !     Push failed
```

When I did not specify a `node_version` the build proceeded properly.

**Comment by gjaldon** [comment]
@ntilwalli I'll have to try this out later in my day to see if I can reproduce the error.

**Comment by aaronjensen** [comment]
@ntilwalli Try it again, I was able to successfully use 6.9.1

**Comment by ntilwalli** [comment]
@aaronjensen I tried again.  Same error.  This is what my config looks like:
```
node_version=6.9.1
npm_version=3.10.9
phoenix_relative_path=apps/candle
```

**Comment by aaronjensen** [comment]
You might try dropping the `npm_version`, I don't have that.

This is mine (I'm sure much of this is not relevant to your app):

```
clean_cache=false
compile="script/buildpack-compile-assets"
config_vars_to_export=(DATABASE_URL TRACKJS_APPLICATION TRACKJS_TOKEN)
node_version=6.9.1
phoenix_relative_path=.
remove_node=true
```

**Comment by ntilwalli** [comment]
@aaronjensen @gjaldon The key was adding the `remove_node=true`.  After I did that it downloaded 6.9.1 properly and completed fine.  That param does not seem to be documented in the README, it should be.  What does it do?  Does it remove the cached version of node?  Anyway, thanks for the help.  Much appreciated

**Comment by ntilwalli** [comment]
@aaronjensen so odd.  I removed the line and tried it again and it just worked.  I can't explain it.  Maybe there was some LF/CR issue I wasn't seeing.  I hate bugs that fix themselves, cuz they can unfix themselves 😉 Hoping that doesn't happen here.  Anyway, thanks.
