### ISSUE TITLE
Document the "remove_node" config param in the README

### ISSUE THREAD

**Issue by ntilwalli** [gjaldon/heroku-buildpack-phoenix-static#48]
The fix for https://github.com/gjaldon/heroku-buildpack-phoenix-static/issues/46 involved using the `remove_node` param which should be documented in the README.

**Comment by aaronjensen** [comment]
`remove_node` is [documented in the pull request it is in](https://github.com/gjaldon/heroku-buildpack-phoenix-static/pull/36), which is not yet merged. The fact that adding that to your config fixed the problem is an odd coincidence.

**Comment by ntilwalli** [comment]
Odd indeed.  Closing.
