### ISSUE TITLE
Yarn error: "Command "deploy" not found."

### ISSUE THREAD

**Issue by jbrowning** [gjaldon/heroku-buildpack-phoenix-static#86]
We're currently on Phoenix 1.4 + brunch (webpack migration is currently optional) and the changes from #83 cause this error on deploy.

**Comment by jbrowning** [comment]
The root issue here of course is that older default Phoenix package.json files did not contain a `deploy` script. We're old school. :)

**Comment by gjaldon** [comment]
Maybe we can do a check to see if brunch or webpack is used and then run the corresponding script? For the meantime, you can add a custom `compile` file to override the default compile commands. You can refer here https://github.com/gjaldon/heroku-buildpack-phoenix-static#compile

**Comment by behe** [comment]
Maybe just document what to put in compile if it's missing in the installation instructions?

**Comment by jaimeiniesta** [comment]
Same here:

```
remote: sent 60 bytes  received 19 bytes  158.00 bytes/sec
remote: total size is 0  speedup is 0.00
remote:        Running default compile
remote:        npm ERR! missing script: deploy
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /app/.npm/_logs/2019-03-08T15_00_27_106Z-debug.log
remote:  !     Push rejected, failed to compile Phoenix app.
remote:
remote:  !     Push failed
```

**Comment by gjaldon** [comment]
The README has been updated to explain that default compile has been changed and includes what needs to be put in `compile` https://github.com/gjaldon/heroku-buildpack-phoenix-static#faq

Let me know if this is good enough or needs some changes.

**Comment by jbrowning** [comment]
Good enough for me.

Many thanks.

**Comment by jaimeiniesta** [comment]
Thanks but it didn't work for me:

``` 
remote: sent 63 bytes  received 19 bytes  164.00 bytes/sec
remote: total size is 0  speedup is 0.00
remote:        Running custom compile
remote:        /tmp/build_69cbbfe227fbf89defae65a3701c72e5/compile: line 1: brunch: command not found
remote:  !     Push rejected, failed to compile Phoenix app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
```
